/**
 * @Description : description en anglais des méthodes que l'on trouve dans cette classe
 * @Version : version de la classe sous la forme a.b.c avec a version majeur, b version mineur et c correctif
 * @CreatedDate : date de création de la classe sous la forme aaaa-mm-jj
 * @LastModifiedDate : date de la dernière modification de la classe sous la forme aaaa-mm-jj
 * @Commentary : commentaire synthétique en anglais des 5 dernières modifications réalisés dans cette classe
 */
public with sharing class THXXX_NomDeLObjet {
	// Constructors of the class THXXX_NomDeLObjet
	public THXXX_NomDeLObjet(){
	}

	// Methods of the class THXXX_NomDeLObjet
	public void nomDeMethodeStatique(){
		return;
	}

	public static void NomDeMethodeStatique(){
		return;
	}
}